name: Build and Push Docker Image

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image
      run: |
        cd Backend
        docker build -t orbitbot-backend .
        
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Push to GitHub Container Registry
      run: |
        docker tag orbitbot-backend ghcr.io/${{ github.repository_owner }}/orbitbot-backend:latest
        docker push ghcr.io/${{ github.repository_owner }}/orbitbot-backend:latest
        docker tag orbitbot-backend ghcr.io/${{ github.repository_owner }}/orbitbot-backend:${{ github.sha }}
        docker push ghcr.io/${{ github.repository_owner }}/orbitbot-backend:${{ github.sha }}
