name: Build and Push Docker Image

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image (Stable)
      run: |
        cd Backend
        docker build -f Dockerfile.stable -t orbitbot-backend .
        
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Push to GitHub Container Registry
      run: |
        # Convert repository name to lowercase for GHCR compatibility
        REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        docker tag orbitbot-backend ghcr.io/$REPO_NAME/orbitbot-backend:latest
        docker push ghcr.io/$REPO_NAME/orbitbot-backend:latest
        docker tag orbitbot-backend ghcr.io/$REPO_NAME/orbitbot-backend:${{ github.sha }}
        docker push ghcr.io/$REPO_NAME/orbitbot-backend:${{ github.sha }}
